<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Lab03_02</RootNamespace>
    <AssemblyName>Lab03_02</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="MainForm.Designer.cs">
      <DependentUpon>MainForm.cs</DependentUpon>
    </Compile>
  </ItemGroup>

</Project>
